### ISSUE TITLE
Not Working on android 

### ISSUE THREAD

**Issue by taatiq882** [likashefqet/react-native-image-zoom#11]
**Describe the bug**
I have already integrated the reanimated and gesture handler and both are working on android. But on android its showing the image but its not reacting to the gesture on the image for example pinch to zoom although everything is working fine on ios.

`<ImageZoom uri={imagePath} />`

**Comment by likashefqet** [comment]
**Can you provide more details please?**

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by rkostrab** [comment]
@taatiq882 I see that you were looking for the same pinch to zoom library over the internet. How did you resolved it please?

**Comment by vietnt-uet** [comment]
@taatiq882 Maybe you need wrap your component or screen with a HOC of react-native-gesture-handler?

**Comment by liptonzuma** [comment]
I have wrapped my component in the HOC but still not working on android

**Comment by liptonzuma** [comment]
`import {
  StyleSheet,
  Text,
  View,
  TouchableWithoutFeedback,
  Dimensions,
  TouchableOpacity,
} from 'react-native';
import React, {useContext, useEffect, useState} from 'react';
import colors from '../../../shared/colors';
import fonts from '../../../shared/fonts';
import languageContext from '../../../contexts/language.context';
import {useTranslation} from 'react-i18next';
import {Image} from 'react-native-elements';
import {BottomSheet} from 'react-native-elements';
import {ImageZoom} from '@likashefqet/react-native-image-zoom';
import {gestureHandlerRootHOC} from 'react-native-gesture-handler';

const OrderDetails = gestureHandlerRootHOC(() => {
  const {ticketDetail, setTickDetail} = useContext(languageContext);

  const [present, setPresent] = useState(false);
  const [showMe, setShowMe] = useState(null);

  const {t} = useTranslation();

  useEffect(() => {
    console.log('lala', ticketDetail.ticket_Details);
  }, []);

  return (
    <View style={styles.container}>
      <BottomSheet
        isVisible={present}
        containerStyle={{flex: 1, height: '100%'}}>
        <TouchableWithoutFeedback onPress={() => setPresent(false)}>
          <View
            style={{
              flex: 1,
              height: Dimensions.get('window').height,
              alignItems: 'center',
              justifyContent: 'center',
            }}>
            <ImageZoom
              source={{uri: showMe}}
              resizeMode="contain"
              style={{
                width: 287,
                height: 371,
                alignSelf: 'center',
              }}
              minScale={1}
              maxScale={5}
            />
          </View>
        </TouchableWithoutFeedback>
      </BottomSheet>
      {/* client name */}
      <View style={[styles.row, {marginTop: 0}]}>
        <Text style={styles.key}>{t('client')}</Text>
        <Text style={styles.value}>{ticketDetail.data.customer_name}</Text>
      </View>
      {/* date */}
      <View style={styles.row}>
        <Text style={styles.key}>{t('date')}</Text>
        <Text style={[styles.value, {textTransform: 'none'}]}>
          {ticketDetail.ticket_Details.ticket_info.booking_date}
        </Text>
      </View>
      {/* time */}
      <View style={styles.row}>
        <Text style={styles.key}>{t('time')}</Text>
        <Text style={[styles.value, {textTransform: 'none'}]}>
          {ticketDetail.ticket_Details.ticket_info.time_slot}
        </Text>
      </View>
      {/* estimation */}
      {/* <View style={styles.row}>
        <Text style={styles.key}>{t('estimation')}</Text>
        <Text style={styles.value}>
          {ticketDetail.ticket_Details.ticket_info.estimation_allow
            ? ticketDetail.ticket_Details.ticket_info.estimation_allow
            : 'fixed'}
        </Text>
      </View> */}
      {/* payment */}
      <View style={styles.row}>
        <Text style={styles.key}>{t('payment')}</Text>
        <Text style={styles.value}>
          {ticketDetail.ticket_Details.charges_info.payment_mode}
        </Text>
      </View>
      {/* charges */}

      {/* charges after discount */}
      <View style={styles.row}>
        <Text style={styles.key}>{t('additional charges')}</Text>
        <Text style={styles.value}>
          {ticketDetail.ticket_Details.charges_info.additional_charge}{' '}
          <Text style={{textTransform: 'uppercase'}}>KWD</Text>
        </Text>
      </View>

      <View style={styles.row}>
        <Text style={styles.key}>{t('service charge')}</Text>
        <Text style={styles.value}>
          {ticketDetail.ticket_Details.charges_info.service_charge}{' '}
          <Text style={{textTransform: 'uppercase'}}>KWD</Text>
        </Text>
      </View>

      <View style={styles.row}>
        <Text style={styles.key}>{t('discount amount')}</Text>
        <Text style={styles.value}>
          {ticketDetail.ticket_Details.charges_info.discount_amount}{' '}
          <Text style={{textTransform: 'uppercase'}}>KWD</Text>
        </Text>
      </View>
      <View style={styles.row}>
        <Text style={styles.key}>{t('Total charges')}</Text>
        <Text style={styles.value}>
          {ticketDetail.ticket_Details.charges_info.total_charge}
          <Text style={{textTransform: 'uppercase'}}> KWD</Text>
        </Text>
      </View>

      {/* job description */}
      <View style={styles.headsup}>
        <Text style={[styles.key, {textTransform: 'capitalize'}]}>
          {t('job description')}
        </Text>
        {/* decription text */}
        <Text
          style={[
            styles.value,
            {fontSize: 14, paddingTop: 10, textTransform: 'none'},
          ]}>
          {ticketDetail.ticket_Details.ticket_info.service_comment}
        </Text>

        <View style={styles.images}>
          {ticketDetail.ticket_Details.service_image.map(item => (
            <TouchableOpacity
              key={item.image_id}
              onPress={() => {
                setShowMe(item.full_path);
                setPresent(true);
              }}>
              <Image
                source={{uri: item.full_path}}
                style={styles.image}
                resizeMode={'cover'}
              />
            </TouchableOpacity>
          ))}
        </View>
      </View>
    </View>
  );
});

export default OrderDetails;

const styles = StyleSheet.create({
  image: {
    width: 70,
    height: 70,
    marginRight: 15,
  },
  images: {
    flexDirection: 'row',
    marginTop: 15,
  },
  headsup: {
    borderTopColor: colors.greenDark100,
    borderTopWidth: 1,
    marginVertical: 20,
    paddingTop: 20,
  },
  value: {
    fontFamily: fonts.semiBold,
    fontWeight: '600',
    fontSize: 16,
    color: colors.greenDark800,
    textTransform: 'capitalize',
  },
  key: {
    fontFamily: fonts.regular,
    fontWeight: '400',
    fontSize: 16,
    color: colors.greenDark800,
    textTransform: 'capitalize',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  container: {
    marginTop: 12,
    backgroundColor: colors.white,
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
});
`


This is my code

**Comment by bodrius** [comment]
same issue

**Comment by liptonzuma** [comment]
I was able to solve mine. I was using a modal. So I  changed the modal to a separate screen for zooming and it worked.
So please check if you're using the zoom in a modal, it won't work on android.

**Comment by bodrius** [comment]
> I was able to solve mine. I was using a modal. So I changed the modal to a separate screen for zooming and it worked. So please check if you're using the zoom in a modal, it won't work on android.

Thanks, I will try

**Comment by likashefqet** [comment]
> I was able to solve mine. I was using a modal. So I changed the modal to a separate screen for zooming and it worked. So please check if you're using the zoom in a modal, it won't work on android.

Please make sure to read the docs to get gestures handler working on android https://docs.swmansion.com/react-native-gesture-handler/docs/2.1.1/#usage-with-modals-on-android 

check: https://github.com/likashefqet/react-native-image-zoom/issues/6#issuecomment-1007753770
