### ISSUE TITLE
TypeError: (0 , _reactNativeReanimated.useSharedValue) is not a function

### ISSUE THREAD

**Issue by valery-lavrik** [likashefqet/react-native-image-zoom#13]
After installing the plugin, a stable error

![image](https://user-images.githubusercontent.com/8047999/184600452-2a0799cd-76f8-4baa-9949-91b74133da09.png)

**Comment by demedos** [comment]
Did you follow the [install instructions](https://github.com/likashefqet/react-native-image-zoom#getting-started) on the readme? you seem to miss the reactive-native-reanimated module
