### ISSUE TITLE
Type declarations.ts

### ISSUE THREAD

**Issue by vietnt-uet** [likashefqet/react-native-image-zoom#14]
I'm using Typescript for  my React Native project and after isntall the package I got this warning: 
```
Cannot find module '@likashefqet/react-native-image-zoom' or its corresponding type declarations.ts
```

**Comment by SaraChicaD** [comment]
Have the same problem, so strange.

**Comment by demedos** [comment]
Seems like the index has been placed in the src folder rather than in the root. I'll open a PR if I have time, meanwhile you can just

```ts
import { ImageZoom } from '@likashefqet/react-native-image-zoom/src';
```
