### ISSUE TITLE
ResizeMode for Image

### ISSUE THREAD

**Issue by borstelmannl** [likashefqet/react-native-image-zoom#17]
**Is your feature request related to a problem? Please describe.**
Currently there is no option for the resizeMode of the underlaying image component. So in my case if i make a shared element transition from an image element to the ZoomImage the resizeMode changes and therefor the look of the image.

**Describe the solution you'd like**
Add the prop resizeMode to set the Image resizeMode.

**Comment by dbContext** [comment]
https://github.com/likashefqet/react-native-image-zoom/pull/26
