### ISSUE TITLE
Cannot find module '@likashefqet/react-native-image-zoom' or its corresponding type declarations.ts(2307)

### ISSUE THREAD

**Issue by Goowwy** [likashefqet/react-native-image-zoom#18]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ubugnu** [comment]
Fixed by https://github.com/likashefqet/react-native-image-zoom/pull/19#issue-1637667522
