### ISSUE TITLE
Not working on android :<

### ISSUE THREAD

**Issue by bearfromtheabyss** [likashefqet/react-native-image-zoom#22]
**Describe the bug**
Module works great on iOS but I can't get it working on Android :(

**To Reproduce**
Create a component like that: 
`<ImageZoom resizeMode="contain" minScale={1} maxScale={3} uri={source.uri}/>`

and try to pinch on android, nothing happens.

**Expected behavior**
Properly zooms on android 

**Screenshots**
Can't show it as it's directly connected to pinch

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 - Device: OnePlus Nord
 - OS: Oxygen OS 11.1.11.11.AC01BA
 - Browser - react native app

**Additional context**
My package JSON 
  "dependencies": {
    "@expo/config-plugins": "^6.0.1",
    "@expo/webpack-config": "^18.0.1",
    "@gorhom/bottom-sheet": "^4.4.5",
    "@invertase/react-native-apple-authentication": "^2.2.2",
    "@likashefqet/react-native-image-zoom": "^1.3.0",
    "@react-native-community/netinfo": "9.3.7",
    "@react-native-firebase/app": "^17.5.0",
    "@react-native-firebase/auth": "^17.5.0",
    "@react-native-firebase/database": "^17.5.0",
    "@react-native-firebase/firestore": "^17.5.0",
    "@react-native-firebase/storage": "^17.5.0",
    "@react-navigation/bottom-tabs": "^6.5.5",
    "@react-navigation/native": "^6.1.4",
    "@react-navigation/stack": "^6.3.16",
    "@rneui/base": "^4.0.0-rc.7",
    "@rneui/themed": "^4.0.0-rc.7",
    "@types/react": "~18.0.27",
    "@types/react-native": "~0.70.6",
    "@types/react-native-snap-carousel": "^3.8.5",
    "base-64": "^1.0.0",
    "buffer": "^6.0.3",
    "expo": "~48.0.15",
    "expo-application": "~5.1.1",
    "expo-auth-session": "~4.0.3",
    "expo-build-properties": "~0.6.0",
    "expo-clipboard": "~4.1.2",
    "expo-dev-client": "~2.2.1",
    "expo-image-manipulator": "~11.1.1",
    "expo-image-picker": "~14.1.1",
    "expo-linear-gradient": "~12.1.2",
    "expo-random": "~13.1.1",
    "expo-secure-store": "~12.1.1",
    "expo-splash-screen": "~0.18.2",
    "expo-status-bar": "~1.4.4",
    "expo-system-ui": "~2.2.1",
    "expo-updates": "~0.16.4",
    "expo-web-browser": "~12.1.1",
    "lodash": "^4.17.21",
    "lottie-react-native": "5.1.4",
    "md5": "^2.3.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.71.7",
    "react-native-chart-kit": "^6.12.0",
    "react-native-dotenv": "^3.4.7",
    "react-native-dropdown-picker": "^5.4.4",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-google-mobile-ads": "^9.1.1",
    "react-native-image-marker": "^0.6.3",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-purchases": "^5.13.1",
    "react-native-reanimated": "~2.14.4",
    "react-native-render-html": "^6.3.4",
    "react-native-root-toast": "^3.4.1",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",
    "react-native-share": "^8.2.1",
    "react-native-snap-carousel": "^4.0.0-beta.6",
    "react-native-sse": "^1.1.0",
    "react-native-svg": "13.4.0",
    "react-native-url-polyfill": "^1.3.0",
    "react-native-web": "~0.18.11",
    "typescript": "^4.9.4",
    "zustand": "^4.3.6"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  }
`

**Comment by bearfromtheabyss** [comment]
Ok I can see that android needs a special implementation mentioned here: https://docs.swmansion.com/react-native-gesture-handler/docs/2.1.1/#usage-with-modals-on-android

**Comment by gusgard** [comment]
Worked for me when added `GestureHandlerRootView`

https://docs.swmansion.com/react-native-gesture-handler/docs/guides/migrating-off-rnghenabledroot/#update-your-js-code
