### ISSUE TITLE
Can't zoom in modal

### ISSUE THREAD

**Issue by vuongnh1705** [likashefqet/react-native-image-zoom#32]
I use react-native-modal to wrap image-zoom but zoom not working

**Comment by Quingsley** [comment]
Try to wrap it the ImageZoom component in a view it worked for me on a model but I ma facing  a challenge where when zooming the image snaps back to the original size instead of maintaining the zoom or pinched level of the zoom

**Comment by deleonjulio** [comment]
I solve this issue by using GestureHandlerRootView instead of View
`import { GestureHandlerRootView } from 'react-native-gesture-handler'

;
            <Modal animationType='fade' visible={true}>
                <GestureHandlerRootView  style={{ flex: 1 }}>
                  <ImageZoom 
                      uri={viewImage} 
                      minScale={0.5}
                      maxScale={3}
                      onInteractionStart={() => console.log('Interaction started')}
                      onInteractionEnd={() => console.log('Interaction ended')}
                      onPinchStart={() => console.log('Pinch gesture started')}
                      onPinchEnd={() => console.log('Pinch gesture ended')}
                      onPanStart={() => console.log('Pan gesture started')}
                      onPanEnd={() => console.log('Pan gesture ended')}
                      resize="cover"
                  />
                </GestureHandlerRootView>
            </Modal>

`

**Comment by likashefqet** [comment]
https://github.com/likashefqet/react-native-image-zoom/issues/6#issuecomment-1007753770
> # Usage with modals on Android
> On Android React Native Gesture Handler does not work by default because modals are not located under React Native Root view in native hierarchy. To fix that, components need to be wrapped with gestureHandlerRootHOC (it's no-op on iOS and web).
> 
> [Check official statement here](https://docs.swmansion.com/react-native-gesture-handler/docs/fundamentals/installation/#usage-with-modals-on-android)
> 
> For example:
> 
> ```js
> const ModalContent = gestureHandlerRootHOC(() => (
>   <ImageZoom uri={imageUri}  />
> );
> 
> export default function Example() {
>   return (
>     <Modal>
>       <ModalContent />
>     </Modal>
>   );
> }
> ```
