### ISSUE TITLE
Feature request: Custom component for image instead of uri

### ISSUE THREAD

**Issue by roman-myshchyshyn** [likashefqet/react-native-image-zoom#34]
I already have a component which handles image loading and rendering (I need to provide auth info in order to load an image) and after caching it. Right now it is not posssible to use custom component with this library.

**Comment by antoine-waag** [comment]
@likashefqet do you have some news about this issue ?

Instead of using `Animated.Image`, is not possible to use `Animated.View` and pass a custom image component as children props ? 

It's true that Image component from expo-image is better than react-native, especially for performances.

**Comment by tomhicks** [comment]
This is the only reason I'm not using this library at the moment!

**Comment by LuckyRoc** [comment]
> This is the only reason I'm not using this library at the moment!

any other image zoom library support custom component ?

**Comment by CrowsVeldt** [comment]
I'm interested too

**Comment by likashefqet** [comment]
🎉 Version 4.0.0 of [@likashefqet/react-native-image-zoom](https://www.npmjs.com/package/@likashefqet/react-native-image-zoom) has been released with some exciting new features! 🚀

Feel free to update to the latest version to explore these additions. If you have any more suggestions or ideas for improvements, please feel free to share.

Thank you! 🙌
