### ISSUE TITLE
Support for expo-image or other components

### ISSUE THREAD

**Issue by slytter** [likashefqet/react-native-image-zoom#35]
**Is your feature request related to a problem? Please describe.**
[expo-image](https://docs.expo.dev/versions/latest/sdk/image/#prefetchurls) is beginning to take over `<Image/>` component from react native.

**Describe the solution you'd like**
Instead of making a new exported component maybe we could implement a createZoomComponent, which would make any kind of component zoomable, with your current implementation.

Then you could go:

```
import { createZoomComponent } from 'react-native-image-zoom'
import { Image } from 'expo-image'

const ZoomableImage = createZoomComponent(Image)

const MyComponent = () => {
    return <ZoomableImage 
         // ...expo-image props here
    />
}

```
 
**Describe alternatives you've considered**
Another way would be to implement a `<ZoomableView>{children}</ZoomableView>` kind of component that could just make any child component zoomable.

**Comment by irenerhee** [comment]
I'd be interested in this too!
