### ISSUE TITLE
Simple onPress handler?

### ISSUE THREAD

**Issue by timothyerwin** [likashefqet/react-native-image-zoom#36]
Is is possible to get an event for a simple onPress? Like, if the image is just tapped once?

**Comment by likashefqet** [comment]
🎉 Version 3.0.0 of [@likashefqet/react-native-image-zoom](https://www.npmjs.com/package/@likashefqet/react-native-image-zoom) has been released with some exciting new features! 🚀

Feel free to update to the latest version to explore these additions. If you have any more suggestions or ideas for improvements, please feel free to share.

Thank you! 🙌
