### ISSUE TITLE
ExceptionsManager.js:184 TypeError: (0 , _reactNativeReanimated.useSharedValue) is not a function

### ISSUE THREAD

**Issue by rvera** [likashefqet/react-native-image-zoom#37]
**Describe the bug**
When trying to use this plugin I get the following error:
```ExceptionsManager.js:184 TypeError: (0 , _reactNativeReanimated.useSharedValue) is not a function```

I assume this plugin requires a specific minimum version of react maybe? would be good to specify in the readme

**To Reproduce**
Install the plugin, run the example

**Expected behavior**
It shoould work

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - React Native 0.66.5

**Comment by likashefqet** [comment]
This seems like a setup issue with Reanimated. 
Make sure you've installed it correctly by following all the installation steps, including those for other dependencies. 

```json
"peerDependencies": {
    "react": ">=16.x.x",
    "react-native": ">=0.62.x",
    "react-native-gesture-handler": ">=2.x.x",
    "react-native-reanimated": ">=2.x.x"
},
```

Closing this issue for now; feel free to reopen if needed.
