### ISSUE TITLE
onSnapBackEnd / onResetEnd

### ISSUE THREAD

**Issue by hfllr** [likashefqet/react-native-image-zoom#40]
**Is your feature request related to a problem? Please describe.**
I am conditionally displaying elements over the image component: they disappear as soon as there is zoom-interaction and reappear after. But currently they already appear once the finger-interaction ends and it would look much better if they would only reappear once the image is fully reset to its initial position.

**Describe the solution you'd like**
The same callback as all the other on...End functions but called once the image is fully reset to its initial position.

This little add-on would be amazing and much appreciated if its not too much effort as it would greatly improve the UX

**Comment by likashefqet** [comment]
[Release 2.2.0](https://github.com/likashefqet/react-native-image-zoom/releases/tag/v2.2.0)

**Comment by hfllr** [comment]
> [Release 2.2.0](https://github.com/likashefqet/react-native-image-zoom/releases/tag/v2.2.0)

works like a charm! thank you so much <3
