### ISSUE TITLE
Is it possible to cancel the zoom reset? 

### ISSUE THREAD

**Issue by Tzach123** [likashefqet/react-native-image-zoom#42]

**Comment by likashefqet** [comment]
Check out the [2.0.0-alpha.0](https://www.npmjs.com/package/@likashefqet/react-native-image-zoom/v/2.0.0-alpha.0) version. This release features a handy double-tap zoom functionality. You can zoom in manually or by double tapping. What's neat is that it remembers where you zoomed in, and you can zoom out manually or by double tapping again.

Give it a shot, and tell me how it works for you. I'm also planning to include it in a new release, potentially version 3.0.

**Comment by theprashant-one** [comment]
Hey @likashefqet any update or ETA on 3.0?. Thanks

**Comment by likashefqet** [comment]
🎉 Version 3.0.0 of [@likashefqet/react-native-image-zoom](https://www.npmjs.com/package/@likashefqet/react-native-image-zoom) has been released with some exciting new features! 🚀

Feel free to update to the latest version to explore these additions. If you have any more suggestions or ideas for improvements, please feel free to share.

Thank you! 🙌
