### ISSUE TITLE
The package supposed to work with `react-native-reanimated-carousel` ? 

### ISSUE THREAD

**Issue by IlanAMG** [likashefqet/react-native-image-zoom#43]
ImageZoom not working when used in the carousel

https://github.com/dohooo/react-native-reanimated-carousel

**Comment by xiaoosnggao** [comment]
mark

**Comment by yashgada** [comment]
Any directions on how I can use this lib with a horizontal flatlist?
Basically I want to be able to zoom and all, but also be able to swipe to get to the next picture

**Comment by yashgada** [comment]
Any directions on how I can use this lib with a horizontal flatlist?
Basically I want to be able to zoom and all, but also be able to swipe to get to the next picture

**Comment by yashgada** [comment]
Any directions on how I can use this lib with a horizontal flatlist?
Basically I want to be able to zoom and all, but also be able to swipe to get to the next picture

**Comment by arnabJ** [comment]
@yashgada I was able to make it work with https://github.com/dohooo/react-native-reanimated-carousel but it's too laggy for me on the emulator.

See if you can figure it out to make it stable.

What I did:
I wrapped the ImageZoom component with GestureHandlerRootView component in the renderItem function.

Note: Here I have shown inline function, but instead I have created a function and used React.memo()

Example:
```JSX
<Carousel
    ref={ref}
    ...
    renderItem={({item, index}) => (
        <GestureHandlerRootView>
            <ImageZoom uri={item.uri} style={{width, height}} resizeMode="contain" />
        </GestureHandlerRootView>
    )}
/>
```

**Comment by SpencerRohan** [comment]
minPanPointers={1} was causing it to not swipe to the next slide for me.

**Comment by likashefqet** [comment]
🎉 Version 4.2.0 of [@likashefqet/react-native-image-zoom](https://www.npmjs.com/package/@likashefqet/react-native-image-zoom) has been released with some exciting new features! 🚀

Feel free to update to the latest version to explore these additions. If you have any more suggestions or ideas for improvements, please feel free to share.

Thank you! 🙌
