### ISSUE TITLE
Get the current scale/zoom level?

### ISSUE THREAD

**Issue by mccahan** [likashefqet/react-native-image-zoom#49]
Is there a good way to be able to read the current scale whenever I need to? I don't see it on the ref, and I do see that there's a `scale = useSharedValue()` in the instance but can't find a way to get at it. I have a few places where I would like to be able to read out the current scale (and probably the `x` and `y` offsets), so I can save them for later.

I have a [PR](https://github.com/likashefqet/react-native-image-zoom/pull/48) in for adding the scale to the `onPinchEnd` callback as a potential fix for one of my specific issues, but putting this note in in case there's a good way to accomplish this now that I'm missing.

**Comment by ghmendonca** [comment]
I also need this feature, @likashefqet any chance you can merge and release this?

**Comment by CrowsVeldt** [comment]
I could use this as well

**Comment by 2xSamurai** [comment]
I too really want this feature. Any way we can achieve this?

**Comment by mbenassarou** [comment]
I need it too please

**Comment by InkAndSteel** [comment]
I also need this feature

**Comment by frozencap** [comment]
yeah this is a dealbreaker

**Comment by diego-laya** [comment]
I need this too

**Comment by Fexxix** [comment]
same here. (this comment doesn't help but i also want it and don't want to use another library since most others haven't been updated in a long time).

**Comment by likashefqet** [comment]
🎉 Version 4.1.0 of [@likashefqet/react-native-image-zoom](https://www.npmjs.com/package/@likashefqet/react-native-image-zoom) has been released with some exciting new features! 🚀

Feel free to update to the latest version to explore these additions. If you have any more suggestions or ideas for improvements, please feel free to share.

Thank you! 🙌
