### ISSUE TITLE
in modal is not working

### ISSUE THREAD

**Issue by MalekZishan** [likashefqet/react-native-image-zoom#52]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MalekZishan** [comment]
please do it

**Comment by DenianFossatti** [comment]
Just follow the docs

https://github.com/likashefqet/react-native-image-zoom#usage-with-modals-on-android
