### ISSUE TITLE
[Feature Request] Disable Snap Back via a dedicated property.

### ISSUE THREAD

**Issue by OwenMelbz** [likashefqet/react-native-image-zoom#55]
**Is your feature request related to a problem? Please describe.**
Our app has inconsistent sized image (by design) and this package makes it super easy to handle all the zooming etc. However the "snap back to level 1" feature after about 1s is frustrating users who are zooming in to inspect imagery then being taken back zoomed out, Currently they have to keep their fingers on the screen to try and inspect them which can be a pain, so we'd like to make this a smoother experience for them.

**Describe the solution you'd like**
It would be great to have a standalone prop that could simply disable the snapping back feature e.g. `snapBack={ true/false }` as this would solve all our problems.

**Describe alternatives you've considered**
We've looked at the `isDoubleTapEnabled` prop which also disables the snap back functionality, however this enables double tap to zoom in/out, which in our scenario conflicts with our "approve" or "unapprove" feature as each time they double tap to approve it, it zooms them out.

**Additional context**
N/A

**Comment by adambremler** [comment]
A workaround for this is to capture the double tap gesture yourself in the parent of the `Zoomable` or `ImageZoom` component.

Something like this:
```
<GestureDetector gesture={Gesture.Tap().numberOfTaps(2)}>
  <Zoomable isDoubleTapEnabled>
    ...
  </Zoomable>
</GestureDetector>
```

This way it won't snap back, but it also won't capture double taps.
