### ISSUE TITLE
Can you add feature where i can get updated scale value on Double tap, and double finger zoom in/out  

### ISSUE THREAD

**Issue by girraj96** [likashefqet/react-native-image-zoom#60]

**Comment by likashefqet** [comment]
🎉 Version 4.2.0 of [@likashefqet/react-native-image-zoom](https://www.npmjs.com/package/@likashefqet/react-native-image-zoom) has been released with some exciting new features! 🚀

Feel free to update to the latest version to explore these additions. If you have any more suggestions or ideas for improvements, please feel free to share.

Thank you! 🙌
