### ISSUE TITLE
How to disable pan bounce on frame edges?

### ISSUE THREAD

**Issue by adriendomoison** [likashefqet/react-native-image-zoom#62]
I would like to allow for a hard stop when zoomed and hitting the edge of the frame, is it currently possible?

https://github.com/user-attachments/assets/4f8acb10-87bc-47b7-a8ff-b063a43120ec

Thank you!

**Comment by likashefqet** [comment]
Unfortunately, it's not possible at the moment, it was added to make sure the image is not moved out of the view with no way of accessing it anymore
