### ISSUE TITLE
[iOS] Prevent the zoomed view from overlaying status bar

### ISSUE THREAD

**Issue by badalsaibo** [likashefqet/react-native-image-zoom#68]
**Is your feature request related to a problem? Please describe.**
Prevent the zoom view from overlaying status bar

**Describe the solution you'd like**
We can have a prop that `shouldOverlayStatusbar`

**Describe alternatives you've considered**

**Additional context**
On iOS when zooming the image, the image goes over the status bar
![simulator_screenshot_C2063B08-C7CB-40A4-9752-EA0DE10EACC8](https://github.com/user-attachments/assets/db7c33da-16b4-4c8e-845a-bdb62b643f88)

**Comment by likashefqet** [comment]
Overflow hidden

**Comment by badalsaibo** [comment]
@likashefqet I added `overflow: hidden` on the container and it fixed the issue. Thanks!

```
      <View className="flex-1 justify-center items-center bg-app-blue-100 overflow-hidden">
        <StyledImageZoom
          uri={url}
          className="w-full h-full"
          resizeMode="contain"
          isDoubleTapEnabled
        />
      </View>
 ```
      
![simulator_screenshot_0E63FC59-2A28-43F0-8CD9-26CA7C2460C5](https://github.com/user-attachments/assets/84294599-2720-4a3d-83c3-881f7ce060c6)
