### ISSUE TITLE
add image ref

### ISSUE THREAD

**Issue by sasweb** [likashefqet/react-native-image-zoom#69]
First of all, thank you for the great package. I really appreciate the work.

However, I need a ref to the actual image. 
As far as I can tell there's no ref at the moment and we can't pass something like a `imageRef` in the props.
It would be very helpful for me because I need more information about the image. Like actual width, height and position in the parent/viewport.

Do you think that's something that makes sense? Is there maybe already anything similar in the code I am missing? Would you be open for PRs to add this functionality?

Thanks!

**Comment by likashefqet** [comment]
Please check out the [ExpoImageZoom](https://github.com/likashefqet/react-native-image-zoom/blob/main/example/src/components/ExpoImageZoom.tsx) example.

You can use the Zoomable component (which is identical to the ImageZoom, but it makes any children zoomable) and render your image as a child and provide the ref to the actual image. Hope that helps.

**Comment by sasweb** [comment]
I see, perfect.
Thank you very much!
