### ISSUE TITLE
Blurry image on Android when zooming

### ISSUE THREAD

**Issue by CostasCF** [likashefqet/react-native-image-zoom#73]
**Describe the bug**
I got some complaints from Android users where the image details are blurry when they zoom in. However on iOS the quality is fine.

**To Reproduce**

1. Try to zoom in any android device using below code. 
```
      <ImageZoom
        source={<PLACE_YOUR_HD_IMAGE_HERE>}
        isDoubleTapEnabled
        isSingleTapEnabled
        minPanPointers={1}
        qualiy={100}
        style={{ resizeMode: "contain", width: "auto" }}
      />
```

**Expected behavior**
When zooming in, the image should be nice and clear.

**Screenshots**
![image](https://github.com/user-attachments/assets/b9512f10-5959-4155-9df3-f91aa4932e87)

**Desktop (please complete the following information):**
 - OS: Android
 - Version: react-native@0.75, @likashefqet/react-native-image-zoom": "^4.2.0",

**Additional context**
Possibly related issues from other repos: 
https://github.com/ascoders/react-native-image-zoom/issues/84 
Possible solutions mentioned in other repos: https://github.com/DylanVann/react-native-fast-image/blob/0439f7190f141e51a391c84890cdd8a7067c6ad3/android/src/main/java/com/dylanvann/fastimage/FastImageViewManager.java#L99 

I don't know if this is applicable to this library, any help with this issue is much appreciated.

**Comment by likashefqet** [comment]
@CostasCF the `ImageZoom` component uses React Native's `Image` component, which automatically resizes images. This resizing behavior is more noticeable on Android, as images are often downscaled more aggressively compared to iOS. Currently, there is no workaround to completely disable the downscaling in `Image.` However, you can specify the resize method using
```ts
resizeMethod={'resize'}
```
which often produces better results compared to the default method `auto` or `scale`.

#

The Expo's `Image` component offers more control. By setting
```ts
allowDownscaling={false}
```
you can disable downscaling and render the image at full quality. There is an example of integrating the Expo Image component with this library in the ***example*** folder.

#

> [!CAUTION]
> These resizing features exist primarily for performance optimization. Disabling downscaling can degrade app performance, especially when handling large images. On lower to mid-range devices, this may even cause crashes due to memory limitations. Use this feature cautiously and test thoroughly.
